### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ajepe** [MattobellNg/sudabelt#1]
- On the hr.leave.type add a custom radio button to show the needed three level of approval; such that the COO will be between the Employee manager and time off Officer approval
- Add an additional status /stage called __validate2__ to the hr.leave.accommodation to the workflow. The validate11 will be the COO approval.
- Add  a custom button for COO approval

**Comment by Matt-OBell** [comment]
I closed this since **Opeyemi** is no more with us
